name: Test
on: [push]
jobs:
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - name: Run Backend Tests
      env:          
          CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}  
      run: scripts/test-backend.sh
