name: Test

on:
  push:
    branches:
      - main
      - "**/feature/**"
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}" >> $GITHUB_ENV

      - name: Debug environment variables
        run: echo "CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}"

      - name: Make entrypoint script executable
        run: chmod +x scripts/docker-cicd-entrypoint.sh

      - name: Make test-backend.sh executable
        run: chmod +x scripts/test-backend.sh

      - name: List files for debugging
        run: ls -R

      - name: Run Backend Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
          CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: scripts/test-backend.sh
